/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1392
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class AggregateSpec {
    'key'?: string;
    'op'?: AggregateSpec.OpEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "op",
            "baseName": "op",
            "type": "AggregateSpec.OpEnum"
        }    ];

    static getAttributeTypeMap() {
        return AggregateSpec.attributeTypeMap;
    }
}

export namespace AggregateSpec {
    export enum OpEnum {
        Sum = <any> 'Sum',
        Proportion = <any> 'Proportion',
        Average = <any> 'Average',
        Count = <any> 'Count',
        Min = <any> 'Min',
        Max = <any> 'Max',
        Value = <any> 'Value'
    }
}
