/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1389
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class AggregationResult {
    'displayName'?: string;
    'scalesWithHoldingQuantity'?: boolean;
    'valueType'?: AggregationResult.ValueTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        },
        {
            "name": "scalesWithHoldingQuantity",
            "baseName": "scalesWithHoldingQuantity",
            "type": "boolean"
        },
        {
            "name": "valueType",
            "baseName": "valueType",
            "type": "AggregationResult.ValueTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return AggregationResult.attributeTypeMap;
    }
}

export namespace AggregationResult {
    export enum ValueTypeEnum {
        String = <any> 'String',
        Int = <any> 'Int',
        Decimal = <any> 'Decimal',
        DateTime = <any> 'DateTime',
        Boolean = <any> 'Boolean',
        Map = <any> 'Map',
        List = <any> 'List',
        PropertyArray = <any> 'PropertyArray',
        Percentage = <any> 'Percentage',
        BenchmarkType = <any> 'BenchmarkType',
        Code = <any> 'Code',
        Id = <any> 'Id',
        Uri = <any> 'Uri',
        ArrayOfIds = <any> 'ArrayOfIds',
        ArrayOfTransactionAliases = <any> 'ArrayOfTransactionAliases',
        ArrayofTransactionMovements = <any> 'ArrayofTransactionMovements',
        ArrayofUnits = <any> 'ArrayofUnits',
        StringArray = <any> 'StringArray',
        CurrencyAndAmount = <any> 'CurrencyAndAmount',
        TradePrice = <any> 'TradePrice',
        UnitCreation = <any> 'UnitCreation',
        Currency = <any> 'Currency',
        UserId = <any> 'UserId',
        MetricValue = <any> 'MetricValue',
        QuoteId = <any> 'QuoteId',
        QuoteSeriesId = <any> 'QuoteSeriesId',
        ResourceId = <any> 'ResourceId',
        ResultValue = <any> 'ResultValue',
        CutLocalTime = <any> 'CutLocalTime',
        DateOrCutLabel = <any> 'DateOrCutLabel',
        Transition = <any> 'Transition',
        StructuredData = <any> 'StructuredData',
        StructuredDataId = <any> 'StructuredDataId',
        ConfigurationRecipe = <any> 'ConfigurationRecipe',
        ConfigurationRecipeSnippet = <any> 'ConfigurationRecipeSnippet',
        StructuredResultDataId = <any> 'StructuredResultDataId',
        StructuredResultData = <any> 'StructuredResultData',
        DataMapping = <any> 'DataMapping',
        LusidInstrument = <any> 'LusidInstrument',
        WeightedInstrument = <any> 'WeightedInstrument',
        Tenor = <any> 'Tenor',
        CdsDetailSpecifications = <any> 'CdsDetailSpecifications',
        FlowConventions = <any> 'FlowConventions',
        OrderId = <any> 'OrderId'
    }
}
