/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1392
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Link } from './link';
import { PerpetualProperty } from './perpetualProperty';
import { ResourceId } from './resourceId';
import { Version } from './version';

/**
* An Allocation of a certain quantity of a specific instrument against an originating  Order.
*/
export class Allocation {
    'id': ResourceId;
    'allocatedOrderId': ResourceId;
    'portfolioId': ResourceId;
    /**
    * The quantity of given instrument allocated.
    */
    'quantity': number;
    /**
    * The instrument allocated.
    */
    'instrumentIdentifiers': { [key: string]: string; };
    'version'?: Version;
    /**
    * Client-defined properties associated with this allocation.
    */
    'properties'?: { [key: string]: PerpetualProperty; };
    /**
    * The LUSID instrument id for the instrument allocated.
    */
    'lusidInstrumentId': string;
    'links'?: Array<Link>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "ResourceId"
        },
        {
            "name": "allocatedOrderId",
            "baseName": "allocatedOrderId",
            "type": "ResourceId"
        },
        {
            "name": "portfolioId",
            "baseName": "portfolioId",
            "type": "ResourceId"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "instrumentIdentifiers",
            "baseName": "instrumentIdentifiers",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "Version"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: PerpetualProperty; }"
        },
        {
            "name": "lusidInstrumentId",
            "baseName": "lusidInstrumentId",
            "type": "string"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<Link>"
        }    ];

    static getAttributeTypeMap() {
        return Allocation.attributeTypeMap;
    }
}

