/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1386
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Link } from './link';
import { ResourceId } from './resourceId';

/**
* The time an entity was modified (amendment and/or historical correction).
*/
export class Change {
    'href'?: string;
    'entityId': ResourceId;
    /**
    * 
    */
    'corrected': boolean;
    /**
    * 
    */
    'correctionEffectiveAt'?: Date;
    /**
    * 
    */
    'correctionAsAt'?: Date;
    /**
    * 
    */
    'amended': boolean;
    /**
    * 
    */
    'amendmentEffectiveAt'?: Date;
    /**
    * 
    */
    'amendmentAsAt'?: Date;
    'links'?: Array<Link>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        },
        {
            "name": "entityId",
            "baseName": "entityId",
            "type": "ResourceId"
        },
        {
            "name": "corrected",
            "baseName": "corrected",
            "type": "boolean"
        },
        {
            "name": "correctionEffectiveAt",
            "baseName": "correctionEffectiveAt",
            "type": "Date"
        },
        {
            "name": "correctionAsAt",
            "baseName": "correctionAsAt",
            "type": "Date"
        },
        {
            "name": "amended",
            "baseName": "amended",
            "type": "boolean"
        },
        {
            "name": "amendmentEffectiveAt",
            "baseName": "amendmentEffectiveAt",
            "type": "Date"
        },
        {
            "name": "amendmentAsAt",
            "baseName": "amendmentAsAt",
            "type": "Date"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<Link>"
        }    ];

    static getAttributeTypeMap() {
        return Change.attributeTypeMap;
    }
}

