/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1389
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class FxOptionAllOf {
    /**
    * The start date of the option.
    */
    'startDate': Date;
    /**
    * The maturity date of the option.
    */
    'optionMaturityDate': Date;
    /**
    * The settlement date of the option.
    */
    'optionSettlementDate': Date;
    /**
    * True of the option is settled in cash false if delivery.
    */
    'isDeliveryNotCash': boolean;
    /**
    * True if the option is a call, false if the option is a put.
    */
    'isCallNotPut': boolean;
    /**
    * The strike of the option.
    */
    'strike': number;
    /**
    * The domestic currency of the FX.
    */
    'domCcy': string;
    /**
    * The foreign currency of the FX.
    */
    'fgnCcy': string;
    /**
    * Instrument type, must be property for JSON.
    */
    'instrumentType': FxOptionAllOf.InstrumentTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "Date"
        },
        {
            "name": "optionMaturityDate",
            "baseName": "optionMaturityDate",
            "type": "Date"
        },
        {
            "name": "optionSettlementDate",
            "baseName": "optionSettlementDate",
            "type": "Date"
        },
        {
            "name": "isDeliveryNotCash",
            "baseName": "isDeliveryNotCash",
            "type": "boolean"
        },
        {
            "name": "isCallNotPut",
            "baseName": "isCallNotPut",
            "type": "boolean"
        },
        {
            "name": "strike",
            "baseName": "strike",
            "type": "number"
        },
        {
            "name": "domCcy",
            "baseName": "domCcy",
            "type": "string"
        },
        {
            "name": "fgnCcy",
            "baseName": "fgnCcy",
            "type": "string"
        },
        {
            "name": "instrumentType",
            "baseName": "instrumentType",
            "type": "FxOptionAllOf.InstrumentTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return FxOptionAllOf.attributeTypeMap;
    }
}

export namespace FxOptionAllOf {
    export enum InstrumentTypeEnum {
        QuotedSecurity = <any> 'QuotedSecurity',
        InterestRateSwap = <any> 'InterestRateSwap',
        FxForward = <any> 'FxForward',
        Exotic = <any> 'Exotic',
        FxOption = <any> 'FxOption',
        CreditDefaultSwap = <any> 'CreditDefaultSwap',
        InterestRateSwaption = <any> 'InterestRateSwaption',
        Bond = <any> 'Bond',
        EquityOption = <any> 'EquityOption',
        Unknown = <any> 'Unknown'
    }
}
