/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1389
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FlowConventions } from './flowConventions';

/**
* The leg of the swap.
*/
export class InstrumentLeg {
    'conventions': FlowConventions;
    /**
    * True if the holder of the swap pays, false if they receive the flows on this leg.
    */
    'isPayNotReceive': boolean;
    /**
    * True if the payments float or are fixed.
    */
    'isFloatNotFixed': boolean;
    /**
    * If the leg is fixed, the fixed rate.
    */
    'fixedRate': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "conventions",
            "baseName": "conventions",
            "type": "FlowConventions"
        },
        {
            "name": "isPayNotReceive",
            "baseName": "isPayNotReceive",
            "type": "boolean"
        },
        {
            "name": "isFloatNotFixed",
            "baseName": "isFloatNotFixed",
            "type": "boolean"
        },
        {
            "name": "fixedRate",
            "baseName": "fixedRate",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return InstrumentLeg.attributeTypeMap;
    }
}

