/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1383
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InstrumentDefinition } from './instrumentDefinition';

/**
* A collection of instrument search results
*/
export class InstrumentMatch {
    /**
    * The collection of instruments found by the search which have been mastered within LUSID.
    */
    'masteredInstruments'?: Array<InstrumentDefinition>;
    /**
    * The collection of instruments found by the search which have not been mastered within LUSID and instead found via OpenFIGI.
    */
    'externalInstruments'?: Array<InstrumentDefinition>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "masteredInstruments",
            "baseName": "masteredInstruments",
            "type": "Array<InstrumentDefinition>"
        },
        {
            "name": "externalInstruments",
            "baseName": "externalInstruments",
            "type": "Array<InstrumentDefinition>"
        }    ];

    static getAttributeTypeMap() {
        return InstrumentMatch.attributeTypeMap;
    }
}

