/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1390
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* It is possible to control which supplier is used for a given asset class.
*/
export class MarketContextSuppliers {
    'commodity'?: MarketContextSuppliers.CommodityEnum;
    'credit'?: MarketContextSuppliers.CreditEnum;
    'equity'?: MarketContextSuppliers.EquityEnum;
    'fx'?: MarketContextSuppliers.FxEnum;
    'rates'?: MarketContextSuppliers.RatesEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "commodity",
            "baseName": "Commodity",
            "type": "MarketContextSuppliers.CommodityEnum"
        },
        {
            "name": "credit",
            "baseName": "Credit",
            "type": "MarketContextSuppliers.CreditEnum"
        },
        {
            "name": "equity",
            "baseName": "Equity",
            "type": "MarketContextSuppliers.EquityEnum"
        },
        {
            "name": "fx",
            "baseName": "Fx",
            "type": "MarketContextSuppliers.FxEnum"
        },
        {
            "name": "rates",
            "baseName": "Rates",
            "type": "MarketContextSuppliers.RatesEnum"
        }    ];

    static getAttributeTypeMap() {
        return MarketContextSuppliers.attributeTypeMap;
    }
}

export namespace MarketContextSuppliers {
    export enum CommodityEnum {
        DataScope = <any> 'DataScope',
        Lusid = <any> 'Lusid',
        Isda = <any> 'Isda',
        Client = <any> 'Client',
        Edi = <any> 'Edi',
        TraderMade = <any> 'TraderMade',
        FactSet = <any> 'FactSet'
    }
    export enum CreditEnum {
        DataScope = <any> 'DataScope',
        Lusid = <any> 'Lusid',
        Isda = <any> 'Isda',
        Client = <any> 'Client',
        Edi = <any> 'Edi',
        TraderMade = <any> 'TraderMade',
        FactSet = <any> 'FactSet'
    }
    export enum EquityEnum {
        DataScope = <any> 'DataScope',
        Lusid = <any> 'Lusid',
        Isda = <any> 'Isda',
        Client = <any> 'Client',
        Edi = <any> 'Edi',
        TraderMade = <any> 'TraderMade',
        FactSet = <any> 'FactSet'
    }
    export enum FxEnum {
        DataScope = <any> 'DataScope',
        Lusid = <any> 'Lusid',
        Isda = <any> 'Isda',
        Client = <any> 'Client',
        Edi = <any> 'Edi',
        TraderMade = <any> 'TraderMade',
        FactSet = <any> 'FactSet'
    }
    export enum RatesEnum {
        DataScope = <any> 'DataScope',
        Lusid = <any> 'Lusid',
        Isda = <any> 'Isda',
        Client = <any> 'Client',
        Edi = <any> 'Edi',
        TraderMade = <any> 'TraderMade',
        FactSet = <any> 'FactSet'
    }
}
