/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1388
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ValueTupleOfMarketDataKeyRuleToQuote } from './valueTupleOfMarketDataKeyRuleToQuote';
import { ValueTupleOfMarketDataKeyRuleToStructuredMarketData } from './valueTupleOfMarketDataKeyRuleToStructuredMarketData';

export class MarketDataManifest {
    'quotes'?: { [key: string]: ValueTupleOfMarketDataKeyRuleToQuote; };
    'structuredMarketData'?: { [key: string]: ValueTupleOfMarketDataKeyRuleToStructuredMarketData; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "quotes",
            "baseName": "quotes",
            "type": "{ [key: string]: ValueTupleOfMarketDataKeyRuleToQuote; }"
        },
        {
            "name": "structuredMarketData",
            "baseName": "structuredMarketData",
            "type": "{ [key: string]: ValueTupleOfMarketDataKeyRuleToStructuredMarketData; }"
        }    ];

    static getAttributeTypeMap() {
        return MarketDataManifest.attributeTypeMap;
    }
}

