/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1387
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AggregationMeasureFailureDetail } from './aggregationMeasureFailureDetail';
import { AggregationResponseNodeOfDictionaryOfStringToObject } from './aggregationResponseNodeOfDictionaryOfStringToObject';
import { Link } from './link';
import { MarketDataManifest } from './marketDataManifest';
import { ResultDataSchema } from './resultDataSchema';

export class NestedAggregationResponse {
    'aggregationEffectiveAt'?: Date;
    'aggregationAsAt'?: Date;
    'href'?: string;
    'data'?: AggregationResponseNodeOfDictionaryOfStringToObject;
    'aggregationCurrency'?: string;
    'dataSchema'?: ResultDataSchema;
    'aggregationFailures'?: Array<AggregationMeasureFailureDetail>;
    'manifest'?: MarketDataManifest;
    'links'?: Array<Link>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "aggregationEffectiveAt",
            "baseName": "aggregationEffectiveAt",
            "type": "Date"
        },
        {
            "name": "aggregationAsAt",
            "baseName": "aggregationAsAt",
            "type": "Date"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "AggregationResponseNodeOfDictionaryOfStringToObject"
        },
        {
            "name": "aggregationCurrency",
            "baseName": "aggregationCurrency",
            "type": "string"
        },
        {
            "name": "dataSchema",
            "baseName": "dataSchema",
            "type": "ResultDataSchema"
        },
        {
            "name": "aggregationFailures",
            "baseName": "aggregationFailures",
            "type": "Array<AggregationMeasureFailureDetail>"
        },
        {
            "name": "manifest",
            "baseName": "manifest",
            "type": "MarketDataManifest"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<Link>"
        }    ];

    static getAttributeTypeMap() {
        return NestedAggregationResponse.attributeTypeMap;
    }
}

