/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1386
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetricValue } from './metricValue';
import { QuoteId } from './quoteId';

/**
* The quote id, value and lineage of the quotes all keyed by a unique correlation id.
*/
export class Quote {
    'quoteId': QuoteId;
    'metricValue'?: MetricValue;
    /**
    * Description of the quote\'s lineage e.g. \'FundAccountant_GreenQuality\'.
    */
    'lineage'?: string;
    /**
    * The cut label that this quote was updated or inserted with.
    */
    'cutLabel'?: string;
    /**
    * The unique id of the user that updated or inserted the quote.
    */
    'uploadedBy': string;
    /**
    * The asAt datetime at which the quote was committed to LUSID.
    */
    'asAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "quoteId",
            "baseName": "quoteId",
            "type": "QuoteId"
        },
        {
            "name": "metricValue",
            "baseName": "metricValue",
            "type": "MetricValue"
        },
        {
            "name": "lineage",
            "baseName": "lineage",
            "type": "string"
        },
        {
            "name": "cutLabel",
            "baseName": "cutLabel",
            "type": "string"
        },
        {
            "name": "uploadedBy",
            "baseName": "uploadedBy",
            "type": "string"
        },
        {
            "name": "asAt",
            "baseName": "asAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Quote.attributeTypeMap;
    }
}

