/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1390
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* An identifier that uniquely describes an item of structured result data such as the risk to an interest curve or a set of yields or analytics on an index.
*/
export class StructuredResultDataId {
    /**
    * The platform or vendor that provided the structured result data, e.g. \'client\'. This is primarily of interest when data could have been sourced from multiple sources
    */
    'source': string;
    /**
    * The identifier for the entity that this id describes. It could be an index, instrument or other form of structured data
    */
    'code'?: string;
    /**
    * The effectiveAt or cut label that this item of structured market data is/was updated/inserted with.
    */
    'effectiveAt'?: string;
    /**
    * An identifier that denotes the class of data that the id points to. This is not the same as the format, but a more generic identifier such as \'risk result\', \'cashflow\', \'index\' or similar.
    */
    'resultType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "source",
            "baseName": "source",
            "type": "string"
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "effectiveAt",
            "baseName": "effectiveAt",
            "type": "string"
        },
        {
            "name": "resultType",
            "baseName": "resultType",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return StructuredResultDataId.attributeTypeMap;
    }
}

