/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1389
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class Tenor {
    'value'?: number;
    'unit'?: Tenor.UnitEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "number"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "Tenor.UnitEnum"
        }    ];

    static getAttributeTypeMap() {
        return Tenor.attributeTypeMap;
    }
}

export namespace Tenor {
    export enum UnitEnum {
        Invalid = <any> 'Invalid',
        BusinessDay = <any> 'BusinessDay',
        Bd = <any> 'Bd',
        Day = <any> 'Day',
        D = <any> 'D',
        Week = <any> 'Week',
        W = <any> 'W',
        Month = <any> 'Month',
        M = <any> 'M',
        Quarter = <any> 'Quarter',
        Q = <any> 'Q',
        Qtr = <any> 'Qtr',
        SemiAnnual = <any> 'SemiAnnual',
        SA = <any> 'SA',
        Year = <any> 'Year',
        Y = <any> 'Y',
        Annual = <any> 'Annual'
    }
}
