/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1387
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SideConfigurationDataRequest } from './sideConfigurationDataRequest';
import { TransactionConfigurationDataRequest } from './transactionConfigurationDataRequest';

/**
* A bundle of requests to configure a set of transaction types.
*/
export class TransactionSetConfigurationDataRequest {
    /**
    * Collection of transaction type models
    */
    'transactionConfigRequests': Array<TransactionConfigurationDataRequest>;
    /**
    * Collection of side definition requests.
    */
    'sideConfigRequests'?: Array<SideConfigurationDataRequest>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "transactionConfigRequests",
            "baseName": "transactionConfigRequests",
            "type": "Array<TransactionConfigurationDataRequest>"
        },
        {
            "name": "sideConfigRequests",
            "baseName": "sideConfigRequests",
            "type": "Array<SideConfigurationDataRequest>"
        }    ];

    static getAttributeTypeMap() {
        return TransactionSetConfigurationDataRequest.attributeTypeMap;
    }
}

