/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1390
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConfigurationRecipe } from './configurationRecipe';
import { ConfigurationRecipeSnippet } from './configurationRecipeSnippet';

/**
* A recipe or recipe snippet that is to be stored in the recipe structured data store.  Only one of these must be present.
*/
export class UpsertRecipeRequest {
    /**
    * User given string name (code) to identify the recipe or snippet for storage in and retrieval from the data store.  Sensibly it would be expected to match the same code given inside the configuration recipe, if that is the element being stored,  though this is not enforced. In the case of a snippet for rules or options, again a sensible naming convention such as options_...  or marketrules_... is advocated to aid in ease of understanding when included elsewhere though not enforced.
    */
    'code': string;
    'configurationRecipe'?: ConfigurationRecipe;
    'configurationRecipeSnippet'?: ConfigurationRecipeSnippet;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "configurationRecipe",
            "baseName": "configurationRecipe",
            "type": "ConfigurationRecipe"
        },
        {
            "name": "configurationRecipeSnippet",
            "baseName": "configurationRecipeSnippet",
            "type": "ConfigurationRecipeSnippet"
        }    ];

    static getAttributeTypeMap() {
        return UpsertRecipeRequest.attributeTypeMap;
    }
}

