/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1387
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StructuredMarketData } from './structuredMarketData';
import { StructuredMarketDataId } from './structuredMarketDataId';

/**
* The details of the structured market data item to upsert into Lusid.
*/
export class UpsertStructuredMarketDataRequest {
    'marketDataId': StructuredMarketDataId;
    'marketData'?: StructuredMarketData;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "marketDataId",
            "baseName": "marketDataId",
            "type": "StructuredMarketDataId"
        },
        {
            "name": "marketData",
            "baseName": "marketData",
            "type": "StructuredMarketData"
        }    ];

    static getAttributeTypeMap() {
        return UpsertStructuredMarketDataRequest.attributeTypeMap;
    }
}

