/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1383
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetricValue } from './metricValue';
import { QuoteId } from './quoteId';

/**
* The details of the quote including its unique identifier, value and lineage.
*/
export class UpsertQuoteRequest {
    'quoteId': QuoteId;
    'metricValue'?: MetricValue;
    /**
    * Description of the quote\'s lineage e.g. \'FundAccountant_GreenQuality\'.
    */
    'lineage'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "quoteId",
            "baseName": "quoteId",
            "type": "QuoteId"
        },
        {
            "name": "metricValue",
            "baseName": "metricValue",
            "type": "MetricValue"
        },
        {
            "name": "lineage",
            "baseName": "lineage",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UpsertQuoteRequest.attributeTypeMap;
    }
}

