/**
 * LUSID API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.10.1386
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ValuationReconciliationRequest } from './valuationReconciliationRequest';

/**
* Specification for the reconciliation request. Left and Right hand sides are constructed. Each consists of a valuation of a portfolio  using an aggregation request. The results of this can then be compared to each other. The difference, which is effectively a risk based  difference allows comparison of the effects of changing a recipe, valuation date, or (though it may or may not make logical sense) a portfolio.  For instance, one might look at the difference in risk caused by the addition of transaction to a portfolio, or through changing the valuation  methodology or system.
*/
export class ValuationsReconciliationRequest {
    'left': ValuationReconciliationRequest;
    'right': ValuationReconciliationRequest;
    /**
    * Instrument properties to be included with any identified breaks. These properties will be in the effective and AsAt dates of the left portfolio
    */
    'instrumentPropertyKeys': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "left",
            "baseName": "left",
            "type": "ValuationReconciliationRequest"
        },
        {
            "name": "right",
            "baseName": "right",
            "type": "ValuationReconciliationRequest"
        },
        {
            "name": "instrumentPropertyKeys",
            "baseName": "instrumentPropertyKeys",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ValuationsReconciliationRequest.attributeTypeMap;
    }
}

