export * from './aggregationApi';
import { AggregationApi } from './aggregationApi';
export * from './allocationsApi';
import { AllocationsApi } from './allocationsApi';
export * from './applicationMetadataApi';
import { ApplicationMetadataApi } from './applicationMetadataApi';
export * from './blocksApi';
import { BlocksApi } from './blocksApi';
export * from './calendarsApi';
import { CalendarsApi } from './calendarsApi';
export * from './complexMarketDataApi';
import { ComplexMarketDataApi } from './complexMarketDataApi';
export * from './configurationRecipeApi';
import { ConfigurationRecipeApi } from './configurationRecipeApi';
export * from './conventionsApi';
import { ConventionsApi } from './conventionsApi';
export * from './corporateActionSourcesApi';
import { CorporateActionSourcesApi } from './corporateActionSourcesApi';
export * from './counterpartiesApi';
import { CounterpartiesApi } from './counterpartiesApi';
export * from './customEntityDefinitionsApi';
import { CustomEntityDefinitionsApi } from './customEntityDefinitionsApi';
export * from './cutLabelDefinitionsApi';
import { CutLabelDefinitionsApi } from './cutLabelDefinitionsApi';
export * from './dataTypesApi';
import { DataTypesApi } from './dataTypesApi';
export * from './derivedTransactionPortfoliosApi';
import { DerivedTransactionPortfoliosApi } from './derivedTransactionPortfoliosApi';
export * from './entitiesApi';
import { EntitiesApi } from './entitiesApi';
export * from './executionsApi';
import { ExecutionsApi } from './executionsApi';
export * from './instrumentsApi';
import { InstrumentsApi } from './instrumentsApi';
export * from './legalEntitiesApi';
import { LegalEntitiesApi } from './legalEntitiesApi';
export * from './loginApi';
import { LoginApi } from './loginApi';
export * from './orderInstructionsApi';
import { OrderInstructionsApi } from './orderInstructionsApi';
export * from './ordersApi';
import { OrdersApi } from './ordersApi';
export * from './packagesApi';
import { PackagesApi } from './packagesApi';
export * from './participationsApi';
import { ParticipationsApi } from './participationsApi';
export * from './personsApi';
import { PersonsApi } from './personsApi';
export * from './placementsApi';
import { PlacementsApi } from './placementsApi';
export * from './portfolioGroupsApi';
import { PortfolioGroupsApi } from './portfolioGroupsApi';
export * from './portfoliosApi';
import { PortfoliosApi } from './portfoliosApi';
export * from './propertyDefinitionsApi';
import { PropertyDefinitionsApi } from './propertyDefinitionsApi';
export * from './quotesApi';
import { QuotesApi } from './quotesApi';
export * from './reconciliationsApi';
import { ReconciliationsApi } from './reconciliationsApi';
export * from './referencePortfolioApi';
import { ReferencePortfolioApi } from './referencePortfolioApi';
export * from './relationDefinitionsApi';
import { RelationDefinitionsApi } from './relationDefinitionsApi';
export * from './relationsApi';
import { RelationsApi } from './relationsApi';
export * from './relationshipDefinitionsApi';
import { RelationshipDefinitionsApi } from './relationshipDefinitionsApi';
export * from './relationshipsApi';
import { RelationshipsApi } from './relationshipsApi';
export * from './schemasApi';
import { SchemasApi } from './schemasApi';
export * from './scopesApi';
import { ScopesApi } from './scopesApi';
export * from './searchApi';
import { SearchApi } from './searchApi';
export * from './structuredMarketDataApi';
import { StructuredMarketDataApi } from './structuredMarketDataApi';
export * from './structuredResultDataApi';
import { StructuredResultDataApi } from './structuredResultDataApi';
export * from './systemConfigurationApi';
import { SystemConfigurationApi } from './systemConfigurationApi';
export * from './transactionPortfoliosApi';
import { TransactionPortfoliosApi } from './transactionPortfoliosApi';
export * from './translationApi';
import { TranslationApi } from './translationApi';

export { RequestFile } from '../model/models';

export const APIS = [AggregationApi, AllocationsApi, ApplicationMetadataApi, BlocksApi, CalendarsApi, ComplexMarketDataApi, ConfigurationRecipeApi, ConventionsApi, CorporateActionSourcesApi, CounterpartiesApi, CustomEntityDefinitionsApi, CutLabelDefinitionsApi, DataTypesApi, DerivedTransactionPortfoliosApi, EntitiesApi, ExecutionsApi, InstrumentsApi, LegalEntitiesApi, LoginApi, OrderInstructionsApi, OrdersApi, PackagesApi, ParticipationsApi, PersonsApi, PlacementsApi, PortfolioGroupsApi, PortfoliosApi, PropertyDefinitionsApi, QuotesApi, ReconciliationsApi, ReferencePortfolioApi, RelationDefinitionsApi, RelationsApi, RelationshipDefinitionsApi, RelationshipsApi, SchemasApi, ScopesApi, SearchApi, StructuredMarketDataApi, StructuredResultDataApi, SystemConfigurationApi, TransactionPortfoliosApi, TranslationApi];
