export * from './aggregationApi';
import { AggregationApi } from './aggregationApi';
export * from './allocationsApi';
import { AllocationsApi } from './allocationsApi';
export * from './applicationMetadataApi';
import { ApplicationMetadataApi } from './applicationMetadataApi';
export * from './calendarsApi';
import { CalendarsApi } from './calendarsApi';
export * from './configurationRecipeApi';
import { ConfigurationRecipeApi } from './configurationRecipeApi';
export * from './conventionsApi';
import { ConventionsApi } from './conventionsApi';
export * from './corporateActionSourcesApi';
import { CorporateActionSourcesApi } from './corporateActionSourcesApi';
export * from './cutLabelDefinitionsApi';
import { CutLabelDefinitionsApi } from './cutLabelDefinitionsApi';
export * from './dataTypesApi';
import { DataTypesApi } from './dataTypesApi';
export * from './derivedTransactionPortfoliosApi';
import { DerivedTransactionPortfoliosApi } from './derivedTransactionPortfoliosApi';
export * from './entitiesApi';
import { EntitiesApi } from './entitiesApi';
export * from './instrumentsApi';
import { InstrumentsApi } from './instrumentsApi';
export * from './legalEntitiesApi';
import { LegalEntitiesApi } from './legalEntitiesApi';
export * from './loginApi';
import { LoginApi } from './loginApi';
export * from './ordersApi';
import { OrdersApi } from './ordersApi';
export * from './personsApi';
import { PersonsApi } from './personsApi';
export * from './portfolioGroupsApi';
import { PortfolioGroupsApi } from './portfolioGroupsApi';
export * from './portfoliosApi';
import { PortfoliosApi } from './portfoliosApi';
export * from './propertyDefinitionsApi';
import { PropertyDefinitionsApi } from './propertyDefinitionsApi';
export * from './quotesApi';
import { QuotesApi } from './quotesApi';
export * from './reconciliationsApi';
import { ReconciliationsApi } from './reconciliationsApi';
export * from './referencePortfolioApi';
import { ReferencePortfolioApi } from './referencePortfolioApi';
export * from './relationDefinitionsApi';
import { RelationDefinitionsApi } from './relationDefinitionsApi';
export * from './relationsApi';
import { RelationsApi } from './relationsApi';
export * from './schemasApi';
import { SchemasApi } from './schemasApi';
export * from './scopesApi';
import { ScopesApi } from './scopesApi';
export * from './searchApi';
import { SearchApi } from './searchApi';
export * from './structuredMarketDataApi';
import { StructuredMarketDataApi } from './structuredMarketDataApi';
export * from './structuredResultDataApi';
import { StructuredResultDataApi } from './structuredResultDataApi';
export * from './systemConfigurationApi';
import { SystemConfigurationApi } from './systemConfigurationApi';
export * from './transactionPortfoliosApi';
import { TransactionPortfoliosApi } from './transactionPortfoliosApi';
export const APIS = [AggregationApi, AllocationsApi, ApplicationMetadataApi, CalendarsApi, ConfigurationRecipeApi, ConventionsApi, CorporateActionSourcesApi, CutLabelDefinitionsApi, DataTypesApi, DerivedTransactionPortfoliosApi, EntitiesApi, InstrumentsApi, LegalEntitiesApi, LoginApi, OrdersApi, PersonsApi, PortfolioGroupsApi, PortfoliosApi, PropertyDefinitionsApi, QuotesApi, ReconciliationsApi, ReferencePortfolioApi, RelationDefinitionsApi, RelationsApi, SchemasApi, ScopesApi, SearchApi, StructuredMarketDataApi, StructuredResultDataApi, SystemConfigurationApi, TransactionPortfoliosApi];
